# Generated by Django 3.0.8 on 2020-07-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('UnitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Units')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
            ],
        ),
    ]
