# Generated by Django 2.2.11 on 2020-07-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0002_stays_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stays',
            new_name='Stay',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Donor')),
                ('unit_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Unit')),
            ],
        ),
    ]
